#!/usr/bin/env bash
set -euo pipefail

if [ "$(id -u)" != 0 ]; then
	echo "Need root, sorry" >&2
	exit 1
fi

cd "$(dirname "$0")"
HOSTNAME="${1:-$(hostname)}"
cd ./hosts/"$HOSTNAME"
nix build .#nixosConfigurations."$HOSTNAME".config.system.build.toplevel --profile /nix/var/nix/profiles/system --no-link --show-trace
/nix/var/nix/profiles/system/bin/switch-to-configuration boot
