#!/usr/bin/env bash
set -euo pipefail

if [ "$(id -u)" != 0 ]; then
	echo "Need root, sorry" >&2
	exit 1
fi

cd "$(dirname "$0")"
HOSTNAME="${1:-$(hostname)}"
# cd ./hosts/"$HOSTNAME"
nix run n#nix-output-monitor -- build --file system.nix "$HOSTNAME".config.system.build.toplevel --profile /nix/var/nix/profiles/system --no-link --show-trace
nix run n#nvd -- diff /run/current-system /nix/var/nix/profiles/system
/nix/var/nix/profiles/system/bin/switch-to-configuration boot
