# @generated by https://codeberg.org/goldstein/unflake
let
  deps = {
    unflake_indirect_nixpkgs = builtins.getFlake "flake:nixpkgs";
  } // rec {
    unflake_github_cachix_git-hooks-nix = builtins.fetchTree {
      type = "github";
      owner = "cachix";
      repo = "git-hooks.nix";
      rev = "49bbbfc218bf3856dfa631cead3b052d78248b83";
      lastModified = 1771858127;
      narHash = "sha256-Gtre9YoYl3n25tJH2AoSdjuwcqij5CPxL3U3xysYD08=";
    };
    unflake_github_cachix_pre-commit-hooks-nix = builtins.fetchTree {
      type = "github";
      owner = "cachix";
      repo = "pre-commit-hooks.nix";
      rev = "49bbbfc218bf3856dfa631cead3b052d78248b83";
      lastModified = 1771858127;
      narHash = "sha256-Gtre9YoYl3n25tJH2AoSdjuwcqij5CPxL3U3xysYD08=";
    };
    unflake_github_edolstra_flake-compat = builtins.fetchTree {
      type = "github";
      owner = "edolstra";
      repo = "flake-compat";
      rev = "5edf11c44bc78a0d334f6334cdaf7d60d732daab";
      lastModified = 1767039857;
      narHash = "sha256-vNpUSpF5Nuw8xvDLj2KCwwksIbjua2LZCqhV1LNRDns=";
    };
    unflake_github_goldsteine_anti-emoji-bot = builtins.fetchTree {
      type = "github";
      owner = "goldsteine";
      repo = "anti-emoji-bot";
      rev = "d1a75e3afcc5d8fbd57e505404f6fd4f89029bd9";
      lastModified = 1766060617;
      narHash = "sha256-JHNk7F8lI5c3bFqrFIyiE779ugT43PJ9AWGeblu5HsE=";
    };
    unflake_github_goldsteine_classified = builtins.fetchTree {
      type = "github";
      owner = "goldsteine";
      repo = "classified";
      rev = "3bb7e22be468efc5a3c1b232d92a41a5a8c33ac0";
      lastModified = 1764756337;
      narHash = "sha256-XX4dxkM0ucoqgavjn78XLrXCrdv+RD4ZZvwZVfvr5ds=";
    };
    unflake_github_goldsteine_flake-templates = builtins.fetchTree {
      type = "github";
      owner = "goldsteine";
      repo = "flake-templates";
      rev = "8d0cc01127c48c01286acb4f72ae72f3ce39e772";
      lastModified = 1659519983;
      narHash = "sha256-j0VDGhNkXEjfv85A6LvHtIoEymzP3CW9IEPpV8wMBUE=";
    };
    unflake_github_goldsteine_inftheory-slides = builtins.fetchTree {
      type = "github";
      owner = "goldsteine";
      repo = "inftheory-slides";
      rev = "72fb619a1a6096c796c192940132fc4cb74972ce";
      lastModified = 1764028492;
      narHash = "sha256-fsl0zqy205HQZoump4eNOQy6ftNvWVVX1dM0nr/ujHU=";
    };
    unflake_github_goldsteine_passnag = builtins.fetchTree {
      type = "github";
      owner = "goldsteine";
      repo = "passnag";
      rev = "71c6750b0e584d6654f73543db84e7d62f1ee320";
      lastModified = 1739563906;
      narHash = "sha256-WgBxYLqlcbj5sGtNkvU/6x0eE6uFdqSIlMFad592MaQ=";
    };
    unflake_github_goldsteine_perlsub = builtins.fetchTree {
      type = "github";
      owner = "goldsteine";
      repo = "perlsub";
      rev = "a39370ad9bda517b689796d83c32801e547bcf8e";
      lastModified = 1738336184;
      narHash = "sha256-HBQ4tOPZe5RtVP4905T58NZiGgzrRPExZkCkpT1vidk=";
    };
    unflake_github_goldsteine_r9ktg = builtins.fetchTree {
      type = "github";
      owner = "goldsteine";
      repo = "r9ktg";
      rev = "7806b1e08b0bc2659331f46ac4963be07d36c940";
      lastModified = 1663411480;
      narHash = "sha256-OajHpmpFa1mD47WsN2UtGjr1RYDXGmRhd3ll/XIJTcU=";
    };
    unflake_github_hercules-ci_flake-parts = builtins.fetchTree {
      type = "github";
      owner = "hercules-ci";
      repo = "flake-parts";
      rev = "57928607ea566b5db3ad13af0e57e921e6b12381";
      lastModified = 1769996383;
      narHash = "sha256-AnYjnFWgS49RlqX7LrC4uA+sCCDBj0Ry/WOJ5XWAsa0=";
    };
    unflake_github_hercules-ci_gitignore-nix = builtins.fetchTree {
      type = "github";
      owner = "hercules-ci";
      repo = "gitignore.nix";
      rev = "cb5e3fdca1de58ccbc3ef53de65bd372b48f567c";
      lastModified = 1762808025;
      narHash = "sha256-XmjITeZNMTQXGhhww6ed/Wacy2KzD6svioyCX7pkUu4=";
    };
    unflake_github_infinidoge_nix-minecraft = builtins.fetchTree {
      type = "github";
      owner = "infinidoge";
      repo = "nix-minecraft";
      rev = "c4e2b8969e09067da9d44b6b5762e1e896418f40";
      lastModified = 1771641457;
      narHash = "sha256-TIekRGfeCwuEmYcWex40RTx0Gd46pqmyUtxdFKb5juI=";
    };
    unflake_github_ipetkov_crane = builtins.fetchTree {
      type = "github";
      owner = "ipetkov";
      repo = "crane";
      rev = "3d3de3313e263e04894f284ac18177bd26169bad";
      lastModified = 1771796463;
      narHash = "sha256-9bCDuUzpwJXcHMQYMS1yNuzYMmKO/CCwCexpjWOl62I=";
    };
    unflake_github_lf-_flakey-profile = builtins.fetchTree {
      type = "github";
      owner = "lf-";
      repo = "flakey-profile";
      rev = "243c903fd8eadc0f63d205665a92d4df91d42d9d";
      lastModified = 1712898590;
      narHash = "sha256-FhGIEU93VHAChKEXx905TSiPZKga69bWl1VB37FK//I=";
    };
    unflake_github_matze_mtheme = builtins.fetchTree {
      type = "github";
      owner = "matze";
      repo = "mtheme";
      rev = "2fa6084b9d34fec9d2d5470eb9a17d0bf712b6c8";
      lastModified = 1533142502;
      narHash = "sha256-1HptXntlCUtXwhKuenuVjsj4K3oK5eOsNPZ9+nwSczg=";
    };
    unflake_github_nix-community_lanzaboote_ref_v0-4-2 = builtins.fetchTree {
      type = "github";
      owner = "nix-community";
      repo = "lanzaboote";
      rev = "a65905a09e2c43ff63be8c0e86a93712361f871e";
      lastModified = 1737639419;
      narHash = "sha256-AEEDktApTEZ5PZXNDkry2YV2k6t0dTgLPEmAZbnigXU=";
    };
    unflake_github_nix-community_fenix = builtins.fetchTree {
      type = "github";
      owner = "nix-community";
      repo = "fenix";
      rev = "2af8ae8bbe91833a54bd3b9cc24c326b66972a8e";
      lastModified = 1771743970;
      narHash = "sha256-eri4eY0fUouYxBgWxJAJzG+xTGXVI7VeNJGcJrqpEt0=";
    };
    unflake_github_nix-community_flake-compat = builtins.fetchTree {
      type = "github";
      owner = "nix-community";
      repo = "flake-compat";
      rev = "4a56054d8ffc173222d09dad23adf4ba946c8884";
      lastModified = 1761640442;
      narHash = "sha256-AtrEP6Jmdvrqiv4x2xa5mrtaIp3OEe8uBYCDZDS+hu8=";
    };
    unflake_github_nix-community_home-manager = builtins.fetchTree {
      type = "github";
      owner = "nix-community";
      repo = "home-manager";
      rev = "9a4b494b1aa1b93d8edf167f46dc8e0c0011280c";
      lastModified = 1771851181;
      narHash = "sha256-gFgE6mGUftwseV3DUENMb0k0EiHd739lZexPo5O/sdQ=";
    };
    unflake_github_nix-community_lib-aggregate = builtins.fetchTree {
      type = "github";
      owner = "nix-community";
      repo = "lib-aggregate";
      rev = "55efa4ba1ddbbe046a4afd17b51867c5348bdce8";
      lastModified = 1771765102;
      narHash = "sha256-RLvOaBEoxgPnGZn9ULbb6xXs98AgiOyPZQpB44XyLvA=";
    };
    unflake_github_nix-community_naersk = builtins.fetchTree {
      type = "github";
      owner = "nix-community";
      repo = "naersk";
      rev = "9d4ed44d8b8cecdceb1d6fd76e74123d90ae6339";
      lastModified = 1769799857;
      narHash = "sha256-88IFXZ7Sa1vxbz5pty0Io5qEaMQMMUPMonLa3Ls/ss4=";
    };
    unflake_github_nix-community_nixpkgs-wayland = builtins.fetchTree {
      type = "github";
      owner = "nix-community";
      repo = "nixpkgs-wayland";
      rev = "2136a73e083d9720bf167826ab3d01f2f4efbb3b";
      lastModified = 1771854704;
      narHash = "sha256-Yr1SibnCpdYrsw9yvrdWUByiKjp4SyyRA2GqMCVgW44=";
    };
    unflake_github_nix-community_nixpkgs-lib = builtins.fetchTree {
      type = "github";
      owner = "nix-community";
      repo = "nixpkgs.lib";
      rev = "36b8fcb216736b0e1869740b324ae521e5df23d8";
      lastModified = 1771723719;
      narHash = "sha256-e+/T/pmEkLP6BHhYjx6GmwP5ivonQQn0bJdH9YrRB+Q=";
    };
    unflake_github_nix-systems_default = builtins.fetchTree {
      type = "github";
      owner = "nix-systems";
      repo = "default";
      rev = "da67096a3b9bf56a91d16901293e51ba5b49a27e";
      lastModified = 1681028828;
      narHash = "sha256-Vy1rq5AaRuLzOxct8nz4T6wlgyUR7zLU309k9mBC768=";
    };
    unflake_github_nixos_nixpkgs_ref_nixos-unstable = builtins.fetchTree {
      type = "github";
      owner = "nixos";
      repo = "nixpkgs";
      rev = "0182a361324364ae3f436a63005877674cf45efb";
      lastModified = 1771369470;
      narHash = "sha256-0NBlEBKkN3lufyvFegY4TYv5mCNHbi5OmBDrzihbBMQ=";
    };
    unflake_github_nixos_flake-compat = builtins.fetchTree {
      type = "github";
      owner = "nixos";
      repo = "flake-compat";
      rev = "5edf11c44bc78a0d334f6334cdaf7d60d732daab";
      lastModified = 1767039857;
      narHash = "sha256-vNpUSpF5Nuw8xvDLj2KCwwksIbjua2LZCqhV1LNRDns=";
    };
    unflake_github_nixos_nixos-hardware = builtins.fetchTree {
      type = "github";
      owner = "nixos";
      repo = "nixos-hardware";
      rev = "740a22363033e9f1bb6270fbfb5a9574067af15b";
      lastModified = 1771423359;
      narHash = "sha256-yRKJ7gpVmXbX2ZcA8nFi6CMPkJXZGjie2unsiMzj3Ig=";
    };
    unflake_github_nmattia_naersk = builtins.fetchTree {
      type = "github";
      owner = "nmattia";
      repo = "naersk";
      rev = "9d4ed44d8b8cecdceb1d6fd76e74123d90ae6339";
      lastModified = 1769799857;
      narHash = "sha256-88IFXZ7Sa1vxbz5pty0Io5qEaMQMMUPMonLa3Ls/ss4=";
    };
    unflake_github_numtide_flake-utils = builtins.fetchTree {
      type = "github";
      owner = "numtide";
      repo = "flake-utils";
      rev = "11707dc2f618dd54ca8739b309ec4fc024de578b";
      lastModified = 1731533236;
      narHash = "sha256-l0KFg5HjrsfsO/JpG+r7fRrqm12kzFHyUHqHCVpMMbI=";
    };
    unflake_github_oxalica_rust-overlay = builtins.fetchTree {
      type = "github";
      owner = "oxalica";
      repo = "rust-overlay";
      rev = "085bdbf5dde5477538e4c87d1684b6c6df56c0ad";
      lastModified = 1771816254;
      narHash = "sha256-vkp3iTF6QmHMvL+34DI93IiMPjS2lqcMlA1fl7nXVsQ=";
    };
    unflake_github_pro-vim_tg-vimhelpbot = builtins.fetchTree {
      type = "github";
      owner = "pro-vim";
      repo = "tg-vimhelpbot";
      rev = "d2aa688d19b6a6c2d30bdab445b4c344edcb752d";
      lastModified = 1750015990;
      narHash = "sha256-s9Vw6CYp0Lx4b21WTHEuxZPJ/ujZME2cv9CPDTlREhM=";
    };
    unflake_github_rust-lang_rust-analyzer_ref_nightly = builtins.fetchTree {
      type = "github";
      owner = "rust-lang";
      repo = "rust-analyzer";
      rev = "0c746f699034e70e1c3f11036b8c2895a0b1071c";
      lastModified = 1771779323;
      narHash = "sha256-V/qjnGSDY/XAzA0LlslvFdksClXrlGZ4vuK7KsDXFKI=";
    };
    unflake_github_rustsec_advisory-db = builtins.fetchTree {
      type = "github";
      owner = "rustsec";
      repo = "advisory-db";
      rev = "c9e6bf916e5979334eefc63a6cba44a880c12654";
      lastModified = 1771830928;
      narHash = "sha256-QZ5+9fvp7dW5qTIOzp7sOFoVd9aOZSViaps6EnsIWzw=";
    };
    unflake_gitlab_simple-nixos-mailserver_blobs = builtins.fetchTree {
      type = "gitlab";
      owner = "simple-nixos-mailserver";
      repo = "blobs";
      rev = "2cccdf1ca48316f2cfd1c9a0017e8de5a7156265";
      lastModified = 1604995301;
      narHash = "sha256-wcLzgLec6SGJA8fx1OEN1yV/Py5b+U5iyYpksUY/yLw=";
    };
    unflake_gitlab_simple-nixos-mailserver_nixos-mailserver = builtins.fetchTree {
      type = "gitlab";
      owner = "simple-nixos-mailserver";
      repo = "nixos-mailserver";
      rev = "781e833633ebc0873d251772a74e4400a73f5d78";
      lastModified = 1770659507;
      narHash = "sha256-RVZno9CypFN3eHxfULKN1K7mb/Cq0HkznnWqnshxpWY=";
    };
    unflake_github_supreeeme_xwayland-satellite = builtins.fetchTree {
      type = "github";
      owner = "supreeeme";
      repo = "xwayland-satellite";
      rev = "33c344fee50504089a447a8fef5878cf4f6215fc";
      lastModified = 1771787042;
      narHash = "sha256-7bM6Y4KldhKnfopSALF8XALxcX7ehkomXH9sPl4MXp0=";
    };
    unflake_github_vim_vim = builtins.fetchTree {
      type = "github";
      owner = "vim";
      repo = "vim";
      rev = "201562401b815ffe573dc8aeb0e34dd209107bec";
      lastModified = 1771790452;
      narHash = "sha256-O0nbPPf+GjJ8tSjkDyKbSztVRFz8JW1116N+kqISEy0=";
    };
    unflake_sourcehut_-goldstein_ln-s = builtins.fetchTree {
      type = "sourcehut";
      owner = "~goldstein";
      repo = "ln-s";
      rev = "1e6adb8e6ea9fd0a89c5ee984f25875ee25d4a51";
      lastModified = 1770387117;
      narHash = "sha256-GL6uDzbnp7vTmlApso7vlTYme4/Yd1//aUlFq36uhh8=";
    };
    unflake_tarball_https---git-lix-systems-lix-project-lix-archive-main-tar-gz = builtins.fetchTree {
      type = "tarball";
      url = "https://git.lix.systems/api/v1/repos/lix-project/lix/archive/864c5e75077a9806a37654bb12aec50160e51da9.tar.gz?rev=864c5e75077a9806a37654bb12aec50160e51da9";
      lastModified = 1771865702;
      narHash = "sha256-Omv7QkDiSTV3CkF6xvbob15Bt3fEN1k7FrVDa9ZDdgU=";
    };
    unflake_tarball_https---git-lix-systems-lix-project-nixos-module-archive-main-tar-gz = builtins.fetchTree {
      type = "tarball";
      url = "https://git.lix.systems/api/v1/repos/lix-project/nixos-module/archive/1688100bba140492658d597f6b307c327f35c780.tar.gz?rev=1688100bba140492658d597f6b307c327f35c780";
      lastModified = 1767364176;
      narHash = "sha256-l6YdEBYQxXjD8ujqvc0tKdwWc3K8UQOi+E4Y3DKQ318=";
    };
    unflake_github_edolstra_flake-compat_flake_false = unflake_github_edolstra_flake-compat;
    unflake_github_matze_mtheme_flake_false = unflake_github_matze_mtheme;
    unflake_github_nixos_flake-compat_flake_false = unflake_github_nixos_flake-compat;
    unflake_github_rust-lang_rust-analyzer_ref_nightly_flake_false = unflake_github_rust-lang_rust-analyzer_ref_nightly;
    unflake_github_rustsec_advisory-db_flake_false = unflake_github_rustsec_advisory-db;
    unflake_gitlab_simple-nixos-mailserver_blobs_flake_false = unflake_gitlab_simple-nixos-mailserver_blobs;
    unflake_github_vim_vim_flake_false = unflake_github_vim_vim;
    unflake_tarball_https---git-lix-systems-lix-project-lix-archive-main-tar-gz_flake_false = unflake_tarball_https---git-lix-systems-lix-project-lix-archive-main-tar-gz;
  };
  universe = rec {
    unflake_indirect_nixpkgs = ((import "${deps.unflake_indirect_nixpkgs.outPath}/flake.nix").outputs {
      self = unflake_indirect_nixpkgs;
    }) // deps.unflake_indirect_nixpkgs // {
      _flake = true;
      outPath = "${deps.unflake_indirect_nixpkgs.outPath}";
      sourceInfo = deps.unflake_indirect_nixpkgs;
    };
    unflake_github_cachix_git-hooks-nix = ((import "${deps.unflake_github_cachix_git-hooks-nix.outPath}/flake.nix").outputs {
      self = unflake_github_cachix_git-hooks-nix;
      flake-compat = unflake_github_nixos_flake-compat_flake_false;
      gitignore = unflake_github_hercules-ci_gitignore-nix;
      nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
    }) // deps.unflake_github_cachix_git-hooks-nix // {
      _flake = true;
      outPath = "${deps.unflake_github_cachix_git-hooks-nix.outPath}";
      sourceInfo = deps.unflake_github_cachix_git-hooks-nix;
    };
    unflake_github_cachix_pre-commit-hooks-nix = ((import "${deps.unflake_github_cachix_pre-commit-hooks-nix.outPath}/flake.nix").outputs {
      self = unflake_github_cachix_pre-commit-hooks-nix;
      flake-compat = unflake_github_nixos_flake-compat_flake_false;
      gitignore = unflake_github_hercules-ci_gitignore-nix;
      nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
    }) // deps.unflake_github_cachix_pre-commit-hooks-nix // {
      _flake = true;
      outPath = "${deps.unflake_github_cachix_pre-commit-hooks-nix.outPath}";
      sourceInfo = deps.unflake_github_cachix_pre-commit-hooks-nix;
    };
    unflake_github_edolstra_flake-compat_flake_false = deps.unflake_github_edolstra_flake-compat_flake_false;
    unflake_github_goldsteine_anti-emoji-bot = ((import "${deps.unflake_github_goldsteine_anti-emoji-bot.outPath}/flake.nix").outputs {
      self = unflake_github_goldsteine_anti-emoji-bot;
      flake-utils = unflake_github_numtide_flake-utils;
      nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
    }) // deps.unflake_github_goldsteine_anti-emoji-bot // {
      _flake = true;
      outPath = "${deps.unflake_github_goldsteine_anti-emoji-bot.outPath}";
      sourceInfo = deps.unflake_github_goldsteine_anti-emoji-bot;
    };
    unflake_github_goldsteine_classified = ((import "${deps.unflake_github_goldsteine_classified.outPath}/flake.nix").outputs {
      self = unflake_github_goldsteine_classified;
      flake-utils = unflake_github_numtide_flake-utils;
      naersk = unflake_github_nix-community_naersk;
      nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
    }) // deps.unflake_github_goldsteine_classified // {
      _flake = true;
      outPath = "${deps.unflake_github_goldsteine_classified.outPath}";
      sourceInfo = deps.unflake_github_goldsteine_classified;
    };
    unflake_github_goldsteine_flake-templates = ((import "${deps.unflake_github_goldsteine_flake-templates.outPath}/flake.nix").outputs {
      self = unflake_github_goldsteine_flake-templates;
    }) // deps.unflake_github_goldsteine_flake-templates // {
      _flake = true;
      outPath = "${deps.unflake_github_goldsteine_flake-templates.outPath}";
      sourceInfo = deps.unflake_github_goldsteine_flake-templates;
    };
    unflake_github_goldsteine_inftheory-slides = ((import "${deps.unflake_github_goldsteine_inftheory-slides.outPath}/flake.nix").outputs {
      self = unflake_github_goldsteine_inftheory-slides;
      flake-utils = unflake_github_numtide_flake-utils;
      metropolis = unflake_github_matze_mtheme_flake_false;
      nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
    }) // deps.unflake_github_goldsteine_inftheory-slides // {
      _flake = true;
      outPath = "${deps.unflake_github_goldsteine_inftheory-slides.outPath}";
      sourceInfo = deps.unflake_github_goldsteine_inftheory-slides;
    };
    unflake_github_goldsteine_passnag = ((import "${deps.unflake_github_goldsteine_passnag.outPath}/flake.nix").outputs {
      self = unflake_github_goldsteine_passnag;
      flake-utils = unflake_github_numtide_flake-utils;
      nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
    }) // deps.unflake_github_goldsteine_passnag // {
      _flake = true;
      outPath = "${deps.unflake_github_goldsteine_passnag.outPath}";
      sourceInfo = deps.unflake_github_goldsteine_passnag;
    };
    unflake_github_goldsteine_perlsub = ((import "${deps.unflake_github_goldsteine_perlsub.outPath}/flake.nix").outputs {
      self = unflake_github_goldsteine_perlsub;
      flake-utils = unflake_github_numtide_flake-utils;
      naersk = unflake_github_nix-community_naersk;
      nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
      rust-overlay = unflake_github_oxalica_rust-overlay;
    }) // deps.unflake_github_goldsteine_perlsub // {
      _flake = true;
      outPath = "${deps.unflake_github_goldsteine_perlsub.outPath}";
      sourceInfo = deps.unflake_github_goldsteine_perlsub;
    };
    unflake_github_goldsteine_r9ktg = ((import "${deps.unflake_github_goldsteine_r9ktg.outPath}/flake.nix").outputs {
      self = unflake_github_goldsteine_r9ktg;
      flake-utils = unflake_github_numtide_flake-utils;
      naersk = unflake_github_nix-community_naersk;
      nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
    }) // deps.unflake_github_goldsteine_r9ktg // {
      _flake = true;
      outPath = "${deps.unflake_github_goldsteine_r9ktg.outPath}";
      sourceInfo = deps.unflake_github_goldsteine_r9ktg;
    };
    unflake_github_hercules-ci_flake-parts = ((import "${deps.unflake_github_hercules-ci_flake-parts.outPath}/flake.nix").outputs {
      self = unflake_github_hercules-ci_flake-parts;
      nixpkgs-lib = unflake_github_nix-community_nixpkgs-lib;
    }) // deps.unflake_github_hercules-ci_flake-parts // {
      _flake = true;
      outPath = "${deps.unflake_github_hercules-ci_flake-parts.outPath}";
      sourceInfo = deps.unflake_github_hercules-ci_flake-parts;
    };
    unflake_github_hercules-ci_gitignore-nix = ((import "${deps.unflake_github_hercules-ci_gitignore-nix.outPath}/flake.nix").outputs {
      self = unflake_github_hercules-ci_gitignore-nix;
      nixpkgs = unflake_indirect_nixpkgs;
    }) // deps.unflake_github_hercules-ci_gitignore-nix // {
      _flake = true;
      outPath = "${deps.unflake_github_hercules-ci_gitignore-nix.outPath}";
      sourceInfo = deps.unflake_github_hercules-ci_gitignore-nix;
    };
    unflake_github_infinidoge_nix-minecraft = ((import "${deps.unflake_github_infinidoge_nix-minecraft.outPath}/flake.nix").outputs {
      self = unflake_github_infinidoge_nix-minecraft;
      flake-compat = unflake_github_edolstra_flake-compat_flake_false;
      nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
      systems = unflake_github_nix-systems_default;
    }) // deps.unflake_github_infinidoge_nix-minecraft // {
      _flake = true;
      outPath = "${deps.unflake_github_infinidoge_nix-minecraft.outPath}";
      sourceInfo = deps.unflake_github_infinidoge_nix-minecraft;
    };
    unflake_github_ipetkov_crane = ((import "${deps.unflake_github_ipetkov_crane.outPath}/flake.nix").outputs {
      self = unflake_github_ipetkov_crane;
    }) // deps.unflake_github_ipetkov_crane // {
      _flake = true;
      outPath = "${deps.unflake_github_ipetkov_crane.outPath}";
      sourceInfo = deps.unflake_github_ipetkov_crane;
    };
    unflake_github_lf-_flakey-profile = ((import "${deps.unflake_github_lf-_flakey-profile.outPath}/flake.nix").outputs {
      self = unflake_github_lf-_flakey-profile;
    }) // deps.unflake_github_lf-_flakey-profile // {
      _flake = true;
      outPath = "${deps.unflake_github_lf-_flakey-profile.outPath}";
      sourceInfo = deps.unflake_github_lf-_flakey-profile;
    };
    unflake_github_matze_mtheme_flake_false = deps.unflake_github_matze_mtheme_flake_false;
    unflake_github_nix-community_lanzaboote_ref_v0-4-2 = ((import "${deps.unflake_github_nix-community_lanzaboote_ref_v0-4-2.outPath}/flake.nix").outputs {
      self = unflake_github_nix-community_lanzaboote_ref_v0-4-2;
      crane = unflake_github_ipetkov_crane;
      flake-compat = unflake_github_edolstra_flake-compat_flake_false;
      flake-parts = unflake_github_hercules-ci_flake-parts;
      nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
      pre-commit-hooks-nix = unflake_github_cachix_pre-commit-hooks-nix;
      rust-overlay = unflake_github_oxalica_rust-overlay;
    }) // deps.unflake_github_nix-community_lanzaboote_ref_v0-4-2 // {
      _flake = true;
      outPath = "${deps.unflake_github_nix-community_lanzaboote_ref_v0-4-2.outPath}";
      sourceInfo = deps.unflake_github_nix-community_lanzaboote_ref_v0-4-2;
    };
    unflake_github_nix-community_fenix = ((import "${deps.unflake_github_nix-community_fenix.outPath}/flake.nix").outputs {
      self = unflake_github_nix-community_fenix;
      nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
      rust-analyzer-src = unflake_github_rust-lang_rust-analyzer_ref_nightly_flake_false;
    }) // deps.unflake_github_nix-community_fenix // {
      _flake = true;
      outPath = "${deps.unflake_github_nix-community_fenix.outPath}";
      sourceInfo = deps.unflake_github_nix-community_fenix;
    };
    unflake_github_nix-community_flake-compat = ((import "${deps.unflake_github_nix-community_flake-compat.outPath}/flake.nix").outputs {
      self = unflake_github_nix-community_flake-compat;
    }) // deps.unflake_github_nix-community_flake-compat // {
      _flake = true;
      outPath = "${deps.unflake_github_nix-community_flake-compat.outPath}";
      sourceInfo = deps.unflake_github_nix-community_flake-compat;
    };
    unflake_github_nix-community_home-manager = ((import "${deps.unflake_github_nix-community_home-manager.outPath}/flake.nix").outputs {
      self = unflake_github_nix-community_home-manager;
      nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
    }) // deps.unflake_github_nix-community_home-manager // {
      _flake = true;
      outPath = "${deps.unflake_github_nix-community_home-manager.outPath}";
      sourceInfo = deps.unflake_github_nix-community_home-manager;
    };
    unflake_github_nix-community_lib-aggregate = ((import "${deps.unflake_github_nix-community_lib-aggregate.outPath}/flake.nix").outputs {
      self = unflake_github_nix-community_lib-aggregate;
      flake-utils = unflake_github_numtide_flake-utils;
      nixpkgs-lib = unflake_github_nix-community_nixpkgs-lib;
    }) // deps.unflake_github_nix-community_lib-aggregate // {
      _flake = true;
      outPath = "${deps.unflake_github_nix-community_lib-aggregate.outPath}";
      sourceInfo = deps.unflake_github_nix-community_lib-aggregate;
    };
    unflake_github_nix-community_naersk = ((import "${deps.unflake_github_nix-community_naersk.outPath}/flake.nix").outputs {
      self = unflake_github_nix-community_naersk;
      fenix = unflake_github_nix-community_fenix;
      nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
    }) // deps.unflake_github_nix-community_naersk // {
      _flake = true;
      outPath = "${deps.unflake_github_nix-community_naersk.outPath}";
      sourceInfo = deps.unflake_github_nix-community_naersk;
    };
    unflake_github_nix-community_nixpkgs-wayland = ((import "${deps.unflake_github_nix-community_nixpkgs-wayland.outPath}/flake.nix").outputs {
      self = unflake_github_nix-community_nixpkgs-wayland;
      flake-compat = unflake_github_nix-community_flake-compat;
      lib-aggregate = unflake_github_nix-community_lib-aggregate;
      nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
    }) // deps.unflake_github_nix-community_nixpkgs-wayland // {
      _flake = true;
      outPath = "${deps.unflake_github_nix-community_nixpkgs-wayland.outPath}";
      sourceInfo = deps.unflake_github_nix-community_nixpkgs-wayland;
    };
    unflake_github_nix-community_nixpkgs-lib = ((import "${deps.unflake_github_nix-community_nixpkgs-lib.outPath}/flake.nix").outputs {
      self = unflake_github_nix-community_nixpkgs-lib;
    }) // deps.unflake_github_nix-community_nixpkgs-lib // {
      _flake = true;
      outPath = "${deps.unflake_github_nix-community_nixpkgs-lib.outPath}";
      sourceInfo = deps.unflake_github_nix-community_nixpkgs-lib;
    };
    unflake_github_nix-systems_default = ((import "${deps.unflake_github_nix-systems_default.outPath}/flake.nix").outputs {
      self = unflake_github_nix-systems_default;
    }) // deps.unflake_github_nix-systems_default // {
      _flake = true;
      outPath = "${deps.unflake_github_nix-systems_default.outPath}";
      sourceInfo = deps.unflake_github_nix-systems_default;
    };
    unflake_github_nixos_nixpkgs_ref_nixos-unstable = ((import "${deps.unflake_github_nixos_nixpkgs_ref_nixos-unstable.outPath}/flake.nix").outputs {
      self = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
    }) // deps.unflake_github_nixos_nixpkgs_ref_nixos-unstable // {
      _flake = true;
      outPath = "${deps.unflake_github_nixos_nixpkgs_ref_nixos-unstable.outPath}";
      sourceInfo = deps.unflake_github_nixos_nixpkgs_ref_nixos-unstable;
    };
    unflake_github_nixos_flake-compat_flake_false = deps.unflake_github_nixos_flake-compat_flake_false;
    unflake_github_nixos_nixos-hardware = ((import "${deps.unflake_github_nixos_nixos-hardware.outPath}/flake.nix").outputs {
      self = unflake_github_nixos_nixos-hardware;
    }) // deps.unflake_github_nixos_nixos-hardware // {
      _flake = true;
      outPath = "${deps.unflake_github_nixos_nixos-hardware.outPath}";
      sourceInfo = deps.unflake_github_nixos_nixos-hardware;
    };
    unflake_github_nmattia_naersk = ((import "${deps.unflake_github_nmattia_naersk.outPath}/flake.nix").outputs {
      self = unflake_github_nmattia_naersk;
      fenix = unflake_github_nix-community_fenix;
      nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
    }) // deps.unflake_github_nmattia_naersk // {
      _flake = true;
      outPath = "${deps.unflake_github_nmattia_naersk.outPath}";
      sourceInfo = deps.unflake_github_nmattia_naersk;
    };
    unflake_github_numtide_flake-utils = ((import "${deps.unflake_github_numtide_flake-utils.outPath}/flake.nix").outputs {
      self = unflake_github_numtide_flake-utils;
      systems = unflake_github_nix-systems_default;
    }) // deps.unflake_github_numtide_flake-utils // {
      _flake = true;
      outPath = "${deps.unflake_github_numtide_flake-utils.outPath}";
      sourceInfo = deps.unflake_github_numtide_flake-utils;
    };
    unflake_github_oxalica_rust-overlay = ((import "${deps.unflake_github_oxalica_rust-overlay.outPath}/flake.nix").outputs {
      self = unflake_github_oxalica_rust-overlay;
      nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
    }) // deps.unflake_github_oxalica_rust-overlay // {
      _flake = true;
      outPath = "${deps.unflake_github_oxalica_rust-overlay.outPath}";
      sourceInfo = deps.unflake_github_oxalica_rust-overlay;
    };
    unflake_github_pro-vim_tg-vimhelpbot = ((import "${deps.unflake_github_pro-vim_tg-vimhelpbot.outPath}/flake.nix").outputs {
      self = unflake_github_pro-vim_tg-vimhelpbot;
      advisory-db = unflake_github_rustsec_advisory-db_flake_false;
      crane = unflake_github_ipetkov_crane;
      fenix = unflake_github_nix-community_fenix;
      flake-utils = unflake_github_numtide_flake-utils;
      nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
      vim = unflake_github_vim_vim_flake_false;
    }) // deps.unflake_github_pro-vim_tg-vimhelpbot // {
      _flake = true;
      outPath = "${deps.unflake_github_pro-vim_tg-vimhelpbot.outPath}";
      sourceInfo = deps.unflake_github_pro-vim_tg-vimhelpbot;
    };
    unflake_github_rust-lang_rust-analyzer_ref_nightly_flake_false = deps.unflake_github_rust-lang_rust-analyzer_ref_nightly_flake_false;
    unflake_github_rustsec_advisory-db_flake_false = deps.unflake_github_rustsec_advisory-db_flake_false;
    unflake_gitlab_simple-nixos-mailserver_blobs_flake_false = deps.unflake_gitlab_simple-nixos-mailserver_blobs_flake_false;
    unflake_gitlab_simple-nixos-mailserver_nixos-mailserver = ((import "${deps.unflake_gitlab_simple-nixos-mailserver_nixos-mailserver.outPath}/flake.nix").outputs {
      self = unflake_gitlab_simple-nixos-mailserver_nixos-mailserver;
      blobs = unflake_gitlab_simple-nixos-mailserver_blobs_flake_false;
      flake-compat = unflake_github_nixos_flake-compat_flake_false;
      git-hooks = unflake_github_cachix_git-hooks-nix;
      nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
    }) // deps.unflake_gitlab_simple-nixos-mailserver_nixos-mailserver // {
      _flake = true;
      outPath = "${deps.unflake_gitlab_simple-nixos-mailserver_nixos-mailserver.outPath}";
      sourceInfo = deps.unflake_gitlab_simple-nixos-mailserver_nixos-mailserver;
    };
    unflake_github_supreeeme_xwayland-satellite = ((import "${deps.unflake_github_supreeeme_xwayland-satellite.outPath}/flake.nix").outputs {
      self = unflake_github_supreeeme_xwayland-satellite;
      nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
      rust-overlay = unflake_github_oxalica_rust-overlay;
    }) // deps.unflake_github_supreeeme_xwayland-satellite // {
      _flake = true;
      outPath = "${deps.unflake_github_supreeeme_xwayland-satellite.outPath}";
      sourceInfo = deps.unflake_github_supreeeme_xwayland-satellite;
    };
    unflake_github_vim_vim_flake_false = deps.unflake_github_vim_vim_flake_false;
    unflake_sourcehut_-goldstein_ln-s = ((import "${deps.unflake_sourcehut_-goldstein_ln-s.outPath}/flake.nix").outputs {
      self = unflake_sourcehut_-goldstein_ln-s;
      nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
    }) // deps.unflake_sourcehut_-goldstein_ln-s // {
      _flake = true;
      outPath = "${deps.unflake_sourcehut_-goldstein_ln-s.outPath}";
      sourceInfo = deps.unflake_sourcehut_-goldstein_ln-s;
    };
    unflake_tarball_https---git-lix-systems-lix-project-lix-archive-main-tar-gz_flake_false = deps.unflake_tarball_https---git-lix-systems-lix-project-lix-archive-main-tar-gz_flake_false;
    unflake_tarball_https---git-lix-systems-lix-project-nixos-module-archive-main-tar-gz = ((import "${deps.unflake_tarball_https---git-lix-systems-lix-project-nixos-module-archive-main-tar-gz.outPath}/flake.nix").outputs {
      self = unflake_tarball_https---git-lix-systems-lix-project-nixos-module-archive-main-tar-gz;
      flake-utils = unflake_github_numtide_flake-utils;
      flakey-profile = unflake_github_lf-_flakey-profile;
      lix = unflake_tarball_https---git-lix-systems-lix-project-lix-archive-main-tar-gz_flake_false;
      nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
    }) // deps.unflake_tarball_https---git-lix-systems-lix-project-nixos-module-archive-main-tar-gz // {
      _flake = true;
      outPath = "${deps.unflake_tarball_https---git-lix-systems-lix-project-nixos-module-archive-main-tar-gz.outPath}";
      sourceInfo = deps.unflake_tarball_https---git-lix-systems-lix-project-nixos-module-archive-main-tar-gz;
    };
  };
  inputs = {
    anti-emoji = universe.unflake_github_goldsteine_anti-emoji-bot;
    classified = universe.unflake_github_goldsteine_classified;
    fenix = universe.unflake_github_nix-community_fenix;
    home-manager = universe.unflake_github_nix-community_home-manager;
    inftheory-slides = universe.unflake_github_goldsteine_inftheory-slides;
    lanzaboote = universe.unflake_github_nix-community_lanzaboote_ref_v0-4-2;
    lix-module = universe.unflake_tarball_https---git-lix-systems-lix-project-nixos-module-archive-main-tar-gz;
    ln-s = universe.unflake_sourcehut_-goldstein_ln-s;
    naersk = universe.unflake_github_nmattia_naersk;
    nix-minecraft = universe.unflake_github_infinidoge_nix-minecraft;
    nixos-hardware = universe.unflake_github_nixos_nixos-hardware;
    nixpkgs = universe.unflake_github_nixos_nixpkgs_ref_nixos-unstable;
    nixpkgs-wayland = universe.unflake_github_nix-community_nixpkgs-wayland;
    passnag = universe.unflake_github_goldsteine_passnag;
    perlsub = universe.unflake_github_goldsteine_perlsub;
    r9ktg = universe.unflake_github_goldsteine_r9ktg;
    simple-nixos-mailserver = universe.unflake_gitlab_simple-nixos-mailserver_nixos-mailserver;
    t = universe.unflake_github_goldsteine_flake-templates;
    tg-vimhelpbot = universe.unflake_github_pro-vim_tg-vimhelpbot;
    xwayland-satellite = universe.unflake_github_supreeeme_xwayland-satellite;
    self = throw "to use inputs.self, write `import ./unflake.nix (inputs: ...)`";
    withInputs = outputs: let self = outputs (inputs // { inherit self; }); in self;
    __functor = self: self.withInputs;
  };
in inputs