return {
    'vito-c/jq.vim',
    { 'cespare/vim-toml', branch = 'main' },
    'ekalinin/Dockerfile.vim',
    'rhysd/vim-llvm',
    'idris-hackers/idris-vim',
    'elixir-editors/vim-elixir',
    'lifepillar/pgsql.vim',
    'LnL7/vim-nix',
    'ziglang/zig.vim',
    { 'zetzit/vim', name = 'zz.vim' },
    'elubow/cql-vim',
    'baskerville/vim-sxhkdrc',
    'BeneCollyridam/futhark-vim',
    'elkowar/yuck.vim',
}
